[tool.black]
exclude = '''
(
  /(
    linien/gateware/logic
   | linien/gateware/lowlevel
   | linien/server/csrmap.py
   | linien\gateware\logic
   | linien\gateware\lowlevel
   | linien\server\csrmap.py
   )/
)
'''

[tool.isort]
profile = "black"