# This is a basic workflow to help you get started with Actions

name: Test-Workflow

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name'
        required: true


env:
  INPUT_VERSION_NAME: ${{ github.event.inputs.version_name }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Print input
        run: echo "The log level is $INPUT_VERSION_NAME"

      - name: create VERSION file
        run: echo "$INPUT_VERSION_NAME" > linien/VERSION

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: ls
        run: ls dist

      - uses: actions/upload-artifact@v2
        with:
          name: my-exe
          path: dist/windows # or path/to/artifact




