name: Pyinstaller Linux

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name'
        required: true


env:
  INPUT_VERSION_NAME: ${{ github.event.inputs.version_name }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create VERSION file
        run: echo "$INPUT_VERSION_NAME" > linien/VERSION

      # NOTE: we hardcode the version of requirements here because the new pip
      #       resolver otherwise takes ages
      # ANOTHER NOTE: scipy is fixed to 1.4.1 because of problems with pyinstaller
      - name: create requirements file
        run: printf "altgraph==0.17\nappdirs==1.4.4\nbcrypt==3.2.0\ncffi==1.14.2\nclick==7.1.2\ncryptography==3.0\nfuture==0.18.2\nnumpy==1.19.1\nparamiko==2.7.1\npefile==2019.4.18\nplumbum==1.6.9\npycparser==2.20\nPyNaCl==1.4.0\nPyQt5==5.15.0\nPyQt5-sip==12.8.0\npyqtgraph==0.11.0\npywin32-ctypes==0.2.0\nrpyc==4.1.5\nscipy==1.4.1\nsix==1.15.0\nuuid==1.30" > requirements.txt

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .

      - uses: actions/upload-artifact@v2
        with:
          name: my-exe
          path: dist/windows



